/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface ContractThatRevertsInterface extends utils.Interface {
  functions: {
    "reason()": FunctionFragment;
    "revertNoReason()": FunctionFragment;
    "revertWithReason(string)": FunctionFragment;
    "setReason(string)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "reason"
      | "revertNoReason"
      | "revertWithReason"
      | "setReason"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "reason", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "revertNoReason",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "revertWithReason",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setReason",
    values: [PromiseOrValue<string>]
  ): string;

  decodeFunctionResult(functionFragment: "reason", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "revertNoReason",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revertWithReason",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setReason", data: BytesLike): Result;

  events: {};
}

export interface ContractThatReverts extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ContractThatRevertsInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    reason(overrides?: CallOverrides): Promise<[string]>;

    revertNoReason(overrides?: CallOverrides): Promise<[void]>;

    revertWithReason(
      reasonMsg: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[void]>;

    setReason(
      reason: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  reason(overrides?: CallOverrides): Promise<string>;

  revertNoReason(overrides?: CallOverrides): Promise<void>;

  revertWithReason(
    reasonMsg: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<void>;

  setReason(
    reason: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    reason(overrides?: CallOverrides): Promise<string>;

    revertNoReason(overrides?: CallOverrides): Promise<void>;

    revertWithReason(
      reasonMsg: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setReason(
      reason: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    reason(overrides?: CallOverrides): Promise<BigNumber>;

    revertNoReason(overrides?: CallOverrides): Promise<BigNumber>;

    revertWithReason(
      reasonMsg: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setReason(
      reason: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    reason(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    revertNoReason(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    revertWithReason(
      reasonMsg: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setReason(
      reason: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
