/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "ERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC20__factory>;
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20__factory>;
    getContractFactory(
      name: "Migrations",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Migrations__factory>;
    getContractFactory(
      name: "Controller",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Controller__factory>;
    getContractFactory(
      name: "MasterMinter",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MasterMinter__factory>;
    getContractFactory(
      name: "MintController",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MintController__factory>;
    getContractFactory(
      name: "MinterManagementInterface",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MinterManagementInterface__factory>;
    getContractFactory(
      name: "ContractThatCallsPublicFunctions",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ContractThatCallsPublicFunctions__factory>;
    getContractFactory(
      name: "ContractThatReverts",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ContractThatReverts__factory>;
    getContractFactory(
      name: "ContractWithExternalFunctions",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ContractWithExternalFunctions__factory>;
    getContractFactory(
      name: "ContractWithPublicFunctions",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ContractWithPublicFunctions__factory>;
    getContractFactory(
      name: "DummyERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.DummyERC20__factory>;
    getContractFactory(
      name: "ECRecoverTest",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ECRecoverTest__factory>;
    getContractFactory(
      name: "EIP712Test",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.EIP712Test__factory>;
    getContractFactory(
      name: "UpgradedFiatToken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.UpgradedFiatToken__factory>;
    getContractFactory(
      name: "UpgradedFiatTokenNewFieldsNewLogicTest",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.UpgradedFiatTokenNewFieldsNewLogicTest__factory>;
    getContractFactory(
      name: "UpgradedFiatTokenNewFieldsTest",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.UpgradedFiatTokenNewFieldsTest__factory>;
    getContractFactory(
      name: "AdminUpgradeabilityProxy",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AdminUpgradeabilityProxy__factory>;
    getContractFactory(
      name: "Proxy",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Proxy__factory>;
    getContractFactory(
      name: "UpgradeabilityProxy",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.UpgradeabilityProxy__factory>;
    getContractFactory(
      name: "FiatTokenV1_1",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.FiatTokenV1_1__factory>;
    getContractFactory(
      name: "Rescuable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Rescuable__factory>;
    getContractFactory(
      name: "AbstractFiatTokenV1",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AbstractFiatTokenV1__factory>;
    getContractFactory(
      name: "Blacklistable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Blacklistable__factory>;
    getContractFactory(
      name: "FiatTokenProxy",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.FiatTokenProxy__factory>;
    getContractFactory(
      name: "FiatTokenV1",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.FiatTokenV1__factory>;
    getContractFactory(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable__factory>;
    getContractFactory(
      name: "Pausable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Pausable__factory>;
    getContractFactory(
      name: "AbstractFiatTokenV2",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AbstractFiatTokenV2__factory>;
    getContractFactory(
      name: "EIP2612",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.EIP2612__factory>;
    getContractFactory(
      name: "EIP3009",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.EIP3009__factory>;
    getContractFactory(
      name: "EIP712Domain",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.EIP712Domain__factory>;
    getContractFactory(
      name: "FiatTokenUtil",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.FiatTokenUtil__factory>;
    getContractFactory(
      name: "FiatTokenV2_1",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.FiatTokenV2_1__factory>;
    getContractFactory(
      name: "FiatTokenV2",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.FiatTokenV2__factory>;
    getContractFactory(
      name: "V2_1Upgrader",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.V2_1Upgrader__factory>;
    getContractFactory(
      name: "V2Upgrader",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.V2Upgrader__factory>;
    getContractFactory(
      name: "V2UpgraderHelper",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.V2UpgraderHelper__factory>;

    getContractAt(
      name: "ERC20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC20>;
    getContractAt(
      name: "IERC20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20>;
    getContractAt(
      name: "Migrations",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Migrations>;
    getContractAt(
      name: "Controller",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Controller>;
    getContractAt(
      name: "MasterMinter",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.MasterMinter>;
    getContractAt(
      name: "MintController",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.MintController>;
    getContractAt(
      name: "MinterManagementInterface",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.MinterManagementInterface>;
    getContractAt(
      name: "ContractThatCallsPublicFunctions",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ContractThatCallsPublicFunctions>;
    getContractAt(
      name: "ContractThatReverts",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ContractThatReverts>;
    getContractAt(
      name: "ContractWithExternalFunctions",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ContractWithExternalFunctions>;
    getContractAt(
      name: "ContractWithPublicFunctions",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ContractWithPublicFunctions>;
    getContractAt(
      name: "DummyERC20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.DummyERC20>;
    getContractAt(
      name: "ECRecoverTest",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ECRecoverTest>;
    getContractAt(
      name: "EIP712Test",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.EIP712Test>;
    getContractAt(
      name: "UpgradedFiatToken",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.UpgradedFiatToken>;
    getContractAt(
      name: "UpgradedFiatTokenNewFieldsNewLogicTest",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.UpgradedFiatTokenNewFieldsNewLogicTest>;
    getContractAt(
      name: "UpgradedFiatTokenNewFieldsTest",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.UpgradedFiatTokenNewFieldsTest>;
    getContractAt(
      name: "AdminUpgradeabilityProxy",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.AdminUpgradeabilityProxy>;
    getContractAt(
      name: "Proxy",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Proxy>;
    getContractAt(
      name: "UpgradeabilityProxy",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.UpgradeabilityProxy>;
    getContractAt(
      name: "FiatTokenV1_1",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.FiatTokenV1_1>;
    getContractAt(
      name: "Rescuable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Rescuable>;
    getContractAt(
      name: "AbstractFiatTokenV1",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.AbstractFiatTokenV1>;
    getContractAt(
      name: "Blacklistable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Blacklistable>;
    getContractAt(
      name: "FiatTokenProxy",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.FiatTokenProxy>;
    getContractAt(
      name: "FiatTokenV1",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.FiatTokenV1>;
    getContractAt(
      name: "Ownable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Ownable>;
    getContractAt(
      name: "Pausable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Pausable>;
    getContractAt(
      name: "AbstractFiatTokenV2",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.AbstractFiatTokenV2>;
    getContractAt(
      name: "EIP2612",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.EIP2612>;
    getContractAt(
      name: "EIP3009",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.EIP3009>;
    getContractAt(
      name: "EIP712Domain",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.EIP712Domain>;
    getContractAt(
      name: "FiatTokenUtil",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.FiatTokenUtil>;
    getContractAt(
      name: "FiatTokenV2_1",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.FiatTokenV2_1>;
    getContractAt(
      name: "FiatTokenV2",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.FiatTokenV2>;
    getContractAt(
      name: "V2_1Upgrader",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.V2_1Upgrader>;
    getContractAt(
      name: "V2Upgrader",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.V2Upgrader>;
    getContractAt(
      name: "V2UpgraderHelper",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.V2UpgraderHelper>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
