/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../common";
import type {
  ContractWithExternalFunctions,
  ContractWithExternalFunctionsInterface,
} from "../../../contracts/test/ContractWithExternalFunctions";

const _abi = [
  {
    inputs: [],
    name: "getBar",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getFoo",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "bar",
        type: "uint256",
      },
    ],
    name: "setBar",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "foo",
        type: "string",
      },
    ],
    name: "setFoo",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b50610349806100206000396000f3fe608060405234801561001057600080fd5b506004361061004c5760003560e01c8063243dc8da14610051578063352d3fba146100ce57806367a23d13146100ff578063cfcb156614610119575b600080fd5b610059610189565b6040805160208082528351818301528351919283929083019185019080838360005b8381101561009357818101518382015260200161007b565b50505050905090810190601f1680156100c05780820380516001836020036101000a031916815260200191505b509250505060405180910390f35b6100eb600480360360208110156100e457600080fd5b503561023d565b604080519115158252519081900360200190f35b610107610245565b60408051918252519081900360200190f35b6100eb6004803603602081101561012f57600080fd5b81019060208101813564010000000081111561014a57600080fd5b82018360208201111561015c57600080fd5b8035906020019184600183028401116401000000008311171561017e57600080fd5b50909250905061024b565b60008054604080516020601f60027fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff6101006001881615020190951694909404938401819004810282018101909252828152606093909290918301828280156102335780601f1061020857610100808354040283529160200191610233565b820191906000526020600020905b81548152906001019060200180831161021657829003601f168201915b5050505050905090565b600190815590565b60015490565b6000610258818484610262565b5060019392505050565b828054600181600116156101000203166002900490600052602060002090601f016020900481019282601f106102c1578280017fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff008235161785556102ee565b828001600101855582156102ee579182015b828111156102ee5782358255916020019190600101906102d3565b506102fa9291506102fe565b5090565b5b808211156102fa57600081556001016102ff56fea2646970667358221220b4df448550aea71ea9693fab3db3757b3ecc9222437cc7e9f680315df2ac670a64736f6c634300060c0033";

type ContractWithExternalFunctionsConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: ContractWithExternalFunctionsConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class ContractWithExternalFunctions__factory extends ContractFactory {
  constructor(...args: ContractWithExternalFunctionsConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractWithExternalFunctions> {
    return super.deploy(
      overrides || {}
    ) as Promise<ContractWithExternalFunctions>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): ContractWithExternalFunctions {
    return super.attach(address) as ContractWithExternalFunctions;
  }
  override connect(signer: Signer): ContractWithExternalFunctions__factory {
    return super.connect(signer) as ContractWithExternalFunctions__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ContractWithExternalFunctionsInterface {
    return new utils.Interface(_abi) as ContractWithExternalFunctionsInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ContractWithExternalFunctions {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as ContractWithExternalFunctions;
  }
}
